version: "3.3"
services:
    app:
        build:
            .
        ports:
            - "8000:8000"
        volumes:
            - ./app:/app
        working_dir:
            /app
        command:
            "flask run --host=0.0.0.0 --port=8000"
        depends_on:
            - db
        environment:
            - DB_NAME=app
            - FLASK_APP=main.py
            - FLASK_ENV=development
        stdin_open:
            true
        tty:
            true
    db:
        image:
            mongo:latest
        volumes:
            - db-data:/data/db
        ports:
            - 27017:27017
        restart:
            unless-stopped
volumes:
    db-data:
